/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 29 12:34:30 GMT 2020
 */

package com.igor.apiDemo;

import org.junit.Test;
import static org.junit.Assert.*;
import com.igor.apiDemo.TesteEvoSuite;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TesteEvoSuite_ESTest extends TesteEvoSuite_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TesteEvoSuite testeEvoSuite0 = new TesteEvoSuite();
      testeEvoSuite0.numThree = 2097;
      testeEvoSuite0.numTwo = (-4431);
      testeEvoSuite0.conditions();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TesteEvoSuite testeEvoSuite0 = new TesteEvoSuite();
      testeEvoSuite0.numThree = (-304);
      testeEvoSuite0.numTwo = (-304);
      testeEvoSuite0.conditions();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TesteEvoSuite testeEvoSuite0 = new TesteEvoSuite();
      testeEvoSuite0.numThree = 0;
      testeEvoSuite0.numTwo = 1;
      testeEvoSuite0.conditions();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TesteEvoSuite testeEvoSuite0 = new TesteEvoSuite();
      testeEvoSuite0.conditions();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TesteEvoSuite testeEvoSuite0 = new TesteEvoSuite();
      testeEvoSuite0.numTwo = 1;
      testeEvoSuite0.conditions();
  }
}
